### ISSUE TITLE
Stops processing after the first match on LG/LM response

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [LeonaMorro/nPose-LM-LG-chains-plugin#2]
`ON_SIT|1|CHAINS_ADD|l_middle~collar~r_middle~collar`

This results in a single chain from the left to the collar front loop because the code stops on the first  match (by using `llListFindList()` rather than a loop.)

**Comment by LeonaMorro** [comment]
The plugin was designed to work with both, the lockmeister and the lockguard protocol. Your line is not lockguard compatible.
Nevertheless since the plugin prefers lockmeister over lockguard it should be able to produce the correct particles (but only if you are using lockmeister collar)
I'm currently not online but after looking into the code I'm almost sure that this is a bug. Could you do me the favour and confirm that you are using a lockmeister compatible collar?
